#pragma once
#ifndef KISAK_RADIANT
#error this file is only for Radiant!
#endif
// Unified undo/redo order for legacy brush/entity, construction, and visibility
// records. Each domain retains its own snapshots and restore implementation.

// Tickets contain only {domain, label}. Record hooks append them when the owning
// store commits a record; undo and redo pop the newest ticket and forward it to
// that store, preserving cross-domain order without copying geometry.

// Legacy eviction and clear hooks remove matching tickets. Before forwarding,
// the journal also asks the authoritative domain store to honor the ticket and
// discards stale tickets until one succeeds.

// KiwiCmd_UndoCancel suppresses the ticket generated while its temporary legacy
// bracket closes and unwinds. Its real Undo_ClearRedo still clears every redo store.
// New work in any domain likewise clears all redo; legacy redo replay suppresses
// the close and redo-clear generated by Undo_Redo itself.

// Hidden state needs its own domain: brushFlags bit 2 and xx5 live on selbrush_t
// instances, while legacy undo snapshots definitions and clears those fields
// when it recreates instances.
enum kundoDomain_t
{
    KUNDO_LEGACY = 0,           // undo.cpp's brush/entity record stack
    KUNDO_CONSTRUCTION,         // kiwi_construct.cpp's whole-store snapshots
    KUNDO_VISIBILITY,           // kiwi_visibility.cpp's hidden-bit snapshots
};

// False lets mainfrm.cpp fall through to classic history predating this journal.
bool KiwiUndo_Undo();
bool KiwiUndo_Redo();

// Journal depths for UI state.
int  KiwiUndo_UndoDepth();
int  KiwiUndo_RedoDepth();
// The newest ticket's label ("drag selection", "draw line"), or NULL.
const char *KiwiUndo_UndoLabel();

// Record hooks. `operation` must have static lifetime because tickets retain it.
void KiwiUndo_NoteLegacyRecord( const char *operation );
void KiwiUndo_NoteConstructionRecord( const char *operation );
void KiwiUndo_NoteVisibilityRecord( const char *operation );   // visibility store tail

// Legacy consistency hooks.
void KiwiUndo_NoteLegacyEvicted();      // Undo_FreeFirstUndo tail — oldest record died
void KiwiUndo_NoteLegacyCleared();      // Undo_Clear tail — the whole legacy stack died
void KiwiUndo_NoteLegacyRedoCleared();  // Undo_ClearRedo tail — the legacy redo died

// Legacy undo clears face selection and recreates covered brushes selected as
// whole objects. KIWI brackets therefore arm a selection snapshot before mutation.
//
// Recreated instances cannot be keyed by pointer. The snapshot records a brush
// ordinal, bounds, face count, face plane, and item indices; restore matches each
// ordinal to the first unused live brush. If no face resolves, legacy selection wins.
//
// Object-only selection remains legacy-owned. Restore also declines while a modal
// command is live so it does not perform another reselect beneath that gesture.
void KiwiUndo_ArmSelectionSnapshot();

// Re-entrant append suppression for KiwiCmd_UndoCancel.
void KiwiUndo_SuppressBegin();
void KiwiUndo_SuppressEnd();

// Drop journal and visibility history during map replacement.
void KiwiUndo_Reset();
